### PR TITLE
side effects set to entry module

### LINKED ISSUE #1235: `sideEffects` should not be `false` now
## 🐛 Bug description
To enable tree-shaking of bundlers, wasm-pack generates `package.json` with `sideEffects: false`. It's OK before since the entry module generated by wasm-bindgen didn't have side effects:

```js
import * as wasm from "./{wasm_name}.wasm";
export * from "./{js_name}.js";
```

But after https://github.com/rustwasm/wasm-bindgen/commit/721c86c3467750bf2a46bf85941e6c211ae9e87a, it now has side effects:

```js
import * as wasm from "./{wasm_name}.wasm";
import { __wbg_set_wasm } from "./{js_name}.js";
__wbg_set_wasm(wasm);
export * from "./{js_name}.js";
```

Now `sideEffects: false` will let bundle remove the `__wbg_set_wasm` call from the entry module, which causes the `let wasm;` variable in binding module to be `undefined`.

#### 🤔 Expected Behavior
What should have happened?

The `sideEffects` property should be set to a list of files with side effects. I think it should be the entry module's filename, i.e. `sideEffects: ["./{entry_name}.js"]`.

#### 👟 Steps to reproduce
Clear steps describing how to reproduce the issue, including commands and flags run. If you are seeing an error, please include the full error message and stack trace.

* [rustwasm-bug-repro.zip](https://github.com/rustwasm/wasm-pack/files/10831720/rustwasm-bug-repro.zip)
* Unzip the project, run `yarn` to install dependencies and run `yarn build` to build a bundle.
* Open `dist/assets/index-*.js`. The file is not minified. You can see the `__wbg_set_wasm` function and assignment to `let wasm;` variable is tree-shaked.
* Modify `node_modules/pkg/package.json` (not `pkg/package.json`, the one to be used by Vite is in node_modules), set `sideEffects` to `["./game_of_life.js"]`.
* Rerun `yarn build`
* Open `dist/assets/index-*.js`. The file is not minified. You can see the `__wbg_set_wasm` function is present and called correctly.

The `pkg` directory in the archive is generated from https://github.com/BLaZeKiLL/game-of-life/tree/69443864176a39415c93c82d361caf2393126b80. With wasm-pack 0.10.3.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.10.3
rustc version: 1.64.0

### PR DESCRIPTION
**Pull request by BLaZeKiLL**
closes #1235
introduced by https://github.com/rustwasm/wasm-bindgen/pull/3152

To remove a circular dependency issue `__wbg_set_wasm ` was added which gets called by the entry module and sets the global wasm variable in our wasm module. since side-effects are set to false our entry module gets tree-shake when using bundlers like Vite or Webpack. hence we can add the entry module to the side-effects array and make sure the wasm initialization is done properly.

I found this issue while following the game of life [tutorial](https://rustwasm.github.io/docs/book/game-of-life/introduction.html)
I had opened a issue on here - https://github.com/rustwasm/wasm-bindgen/issues/3331

Make sure these boxes are checked! 📦✅

- [x] You have the latest version of `rustfmt` installed
```bash
$ rustup component add rustfmt
```
- [x] You ran `cargo fmt` on the code base before submitting
- [x] You reference which issue is being closed in the PR text

✨✨ 😄 Thanks so much for contributing to wasm-pack! 😄 ✨✨

### CODE REVIEW

**Comment by BLaZeKiLL** [comment]
Locally these tests are failing -

```
failures:
    build::build_from_new
    generate::new_with_name_succeeds
    manifest::it_creates_a_pkg_json_with_correct_files_on_node
    manifest::it_creates_a_pkg_json_with_correct_files_on_nomodules
    test::it_can_find_a_webdriver_on_path
    test::it_can_run_browser_tests
```
I don't think these tests are related to my changes since I am pretty new to rust 😅 couldn't figure out how to fix them

env
- M1, OSX 13.2.1
- Rust - 1.67.1
- Cargo - 1.67.1
- Node - 18.13.0
- Yarn - 1.22.19

LOG -
```
---- build::build_from_new stdout ----
Created fixture at /Users/codeblaze/src/rust/wasm-pack/target/t/.tmp5cbEGh/wasm-pack
thread 'build::build_from_new' panicked at 'Unexpected failure.
code-1
stderr=``````
Error: expected value at line 1 column 1
Caused by: expected value at line 1 column 1
```
```
command=`"/Users/codeblaze/src/rust/wasm-pack/target/debug/wasm-pack" "new" "generated-project"`
code=1
stdout=""
stderr=```
Error: expected value at line 1 column 1
Caused by: expected value at line 1 column 1
```

', /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- generate::new_with_name_succeeds stdout ----
Created fixture at /Users/codeblaze/src/rust/wasm-pack/target/t/.tmprhHoXG/wasm-pack
thread 'generate::new_with_name_succeeds' panicked at 'Unexpected failure.
code-1
stderr=``````
Error: expected value at line 1 column 1
Caused by: expected value at line 1 column 1
```
```
command=`"/Users/codeblaze/src/rust/wasm-pack/target/debug/wasm-pack" "new" "hello"`
code=1
stdout=""
stderr=```
Error: expected value at line 1 column 1
Caused by: expected value at line 1 column 1
```

', /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5

---- manifest::it_creates_a_pkg_json_with_correct_files_on_node stdout ----
Created fixture at /Users/codeblaze/src/rust/wasm-pack/target/t/.tmpYq4h4v/wasm-pack
thread 'manifest::it_creates_a_pkg_json_with_correct_files_on_node' panicked at 'called `Result::unwrap()` on an `Err` value: missing field `sideEffects` at line 20 column 1', tests/all/manifest.rs:188:65

---- manifest::it_creates_a_pkg_json_with_correct_files_on_nomodules stdout ----
Created fixture at /Users/codeblaze/src/rust/wasm-pack/target/t/.tmpUt4sYV/wasm-pack
thread 'manifest::it_creates_a_pkg_json_with_correct_files_on_nomodules' panicked at 'called `Result::unwrap()` on an `Err` value: missing field `sideEffects` at line 20 column 1', tests/all/manifest.rs:222:65

---- test::it_can_find_a_webdriver_on_path stdout ----
Created fixture at /Users/codeblaze/src/rust/wasm-pack/target/t/.tmpdSf1VQ/wasm-pack
thread 'test::it_can_find_a_webdriver_on_path' panicked at 'Unexpected failure.
code-1
stderr=``````
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
    Finished dev [unoptimized + debuginfo] target(s) in 0.60s
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
    Finished test [unoptimized + debuginfo] target(s) in 0.56s
     Running unittests src/lib.rs (/Users/codeblaze/src/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/wbg_test_browser-412e83be64a4f76b.wasm)
     Running tests/browser.rs (/Users/codeblaze/src/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/browser-b0da2c9fa5af7b06.wasm)
Error: non-200 response code: 500
{\"value\":{\"error\":\"session not created\",\"message\":\"Expected browser binary location, but unable to find binary in default location, no \'moz:firefoxOptions.binary\' capability provided, and no binary flag set on the command line\",\"stacktrace\":\"\"}}
error: test failed, to rerun pass `--test browser`

Caused by:
  process didn\'t exit successfully: `/Users/codeblaze/src/rust/wasm-pack/target/test_cache/wasm-bindgen-cargo-install-0.2.74/wasm-bindgen-test-runner /Users/codeblaze/src/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/browser-b0da2c9fa5af7b06.wasm` (exit status: 1)
Error: Running Wasm tests with wasm-bindgen-test failed
Caused by: Running Wasm tests with wasm-bindgen-test failed
Caused by: failed to execute `cargo test`: exited with exit status: 1
  full command: \"cargo\" \"test\" \"--target\" \"wasm32-unknown-unknown\"
```
```
command=`"/Users/codeblaze/src/rust/wasm-pack/target/debug/wasm-pack" "test" "--firefox" "--headless" "--mode" "no-install"`
code=1
stdout=```
no tests to run!
                                                  \rSet timeout to 20 seconds...
Executing bindgen...                              \r                                                  \rRunning headless tests in Firefox on `http://127.0.0.1:53718/`
Try find `webdriver.json` for configure browser\'s capabilities:
Not found
Starting new webdriver session...                 \r                                                  \rdriver status: signal: 9 (SIGKILL)
driver stdout:
    1677380707067\tgeckodriver\tINFO\tListening on 127.0.0.1:53718

                                                  \r```

stderr=```
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
    Finished dev [unoptimized + debuginfo] target(s) in 0.60s
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
    Finished test [unoptimized + debuginfo] target(s) in 0.56s
     Running unittests src/lib.rs (/Users/codeblaze/src/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/wbg_test_browser-412e83be64a4f76b.wasm)
     Running tests/browser.rs (/Users/codeblaze/src/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/browser-b0da2c9fa5af7b06.wasm)
Error: non-200 response code: 500
{\"value\":{\"error\":\"session not created\",\"message\":\"Expected browser binary location, but unable to find binary in default location, no \'moz:firefoxOptions.binary\' capability provided, and no binary flag set on the command line\",\"stacktrace\":\"\"}}
error: test failed, to rerun pass `--test browser`

Caused by:
  process didn\'t exit successfully: `/Users/codeblaze/src/rust/wasm-pack/target/test_cache/wasm-bindgen-cargo-install-0.2.74/wasm-bindgen-test-runner /Users/codeblaze/src/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/browser-b0da2c9fa5af7b06.wasm` (exit status: 1)
Error: Running Wasm tests with wasm-bindgen-test failed
Caused by: Running Wasm tests with wasm-bindgen-test failed
Caused by: failed to execute `cargo test`: exited with exit status: 1
  full command: \"cargo\" \"test\" \"--target\" \"wasm32-unknown-unknown\"
```

', /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5

---- test::it_can_run_browser_tests stdout ----
Created fixture at /Users/codeblaze/src/rust/wasm-pack/target/t/.tmp1DljHU/wasm-pack
thread 'test::it_can_run_browser_tests' panicked at 'Unexpected failure.
code-1
stderr=``````
[INFO]: 🎯  Checking for the Wasm target...
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
[INFO]: ⬇\u{fe0f}  Installing wasm-bindgen...
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running unittests src/lib.rs (/Users/codeblaze/src/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/wbg_test_browser-412e83be64a4f76b.wasm)
     Running tests/browser.rs (/Users/codeblaze/src/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/browser-b0da2c9fa5af7b06.wasm)
Error: non-200 response code: 500
{\"value\":{\"error\":\"session not created\",\"message\":\"Expected browser binary location, but unable to find binary in default location, no \'moz:firefoxOptions.binary\' capability provided, and no binary flag set on the command line\",\"stacktrace\":\"\"}}
error: test failed, to rerun pass `--test browser`

Caused by:
  process didn\'t exit successfully: `/Users/codeblaze/src/rust/wasm-pack/target/test_cache/wasm-bindgen-cargo-install-0.2.74/wasm-bindgen-test-runner /Users/codeblaze/src/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/browser-b0da2c9fa5af7b06.wasm` (exit status: 1)
Error: Running Wasm tests with wasm-bindgen-test failed
Caused by: Running Wasm tests with wasm-bindgen-test failed
Caused by: failed to execute `cargo test`: exited with exit status: 1
  full command: \"cargo\" \"test\" \"--target\" \"wasm32-unknown-unknown\"
```
```
command=`"/Users/codeblaze/src/rust/wasm-pack/target/debug/wasm-pack" "test" "--headless" "--firefox" "--safari"`
code=1
stdout=```
no tests to run!
                                                  \rSet timeout to 20 seconds...
Executing bindgen...                              \r                                                  \rRunning headless tests in Firefox on `http://127.0.0.1:53730/`
Try find `webdriver.json` for configure browser\'s capabilities:
Not found
Starting new webdriver session...                 \r                                                  \rdriver status: signal: 9 (SIGKILL)
driver stdout:
    1677380707823\tgeckodriver\tINFO\tListening on 127.0.0.1:53730

                                                  \r```

stderr=```
[INFO]: 🎯  Checking for the Wasm target...
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
[INFO]: ⬇\u{fe0f}  Installing wasm-bindgen...
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running unittests src/lib.rs (/Users/codeblaze/src/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/wbg_test_browser-412e83be64a4f76b.wasm)
     Running tests/browser.rs (/Users/codeblaze/src/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/browser-b0da2c9fa5af7b06.wasm)
Error: non-200 response code: 500
{\"value\":{\"error\":\"session not created\",\"message\":\"Expected browser binary location, but unable to find binary in default location, no \'moz:firefoxOptions.binary\' capability provided, and no binary flag set on the command line\",\"stacktrace\":\"\"}}
error: test failed, to rerun pass `--test browser`

Caused by:
  process didn\'t exit successfully: `/Users/codeblaze/src/rust/wasm-pack/target/test_cache/wasm-bindgen-cargo-install-0.2.74/wasm-bindgen-test-runner /Users/codeblaze/src/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/browser-b0da2c9fa5af7b06.wasm` (exit status: 1)
Error: Running Wasm tests with wasm-bindgen-test failed
Caused by: Running Wasm tests with wasm-bindgen-test failed
Caused by: failed to execute `cargo test`: exited with exit status: 1
  full command: \"cargo\" \"test\" \"--target\" \"wasm32-unknown-unknown\"
```

', /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5

```

**Comment by Menci** [comment]
I created #1236 for it. I kept `sideEffects: false` for `web` target and changed for `bundler` target.

**Comment by Menci** [comment]
Your unit test's failure is because that you added the required field `side_effects` to `struct NpmPackage` without a default value, causing the deserialization failed on other targets than `bundler`. Note that only `bundler` target have the `sideEffects` field.

You can look into my fix and close this one. Anyway, thanks.

**Comment by BLaZeKiLL** [comment]
Ohh, thanks I'll go through it

**Pull request closed without merging**
