### PR TITLE
Remove result prefix and std import, now that quicli is no longer a d…

### LINKED ISSUE #191: Remove outdated quicli comments from `init.rs`
Now that `quicli` is not in the dependencies, the comments above `init::create_pkg_dir` are outdated. Further, I believe the full paths to `result::Result` are no longer needed in the various function/method definitions, since that conflict is no longer caused by `quicli::prelude`.

Assuming I'm right about all of that, I was thinking this could be a pretty straightforward thing to fix, and a good task for someone new to OSS contribution. I can take care of this tomorrow if that sounds good to you, I'll was planning to use it as a pairing exercise with someone :smile:

### PR DESCRIPTION
**Pull request by SoryRawyer**
…ependency

Make sure these boxes are checked! 📦✅

- [x] You have the latest version of `rustfmt` installed and have your 
      cloned directory set to nightly
```bash
$ rustup override set nightly
$ rustup component add rustfmt-preview --toolchain nightly
```
- [x] You ran `rustfmt` on the code base before submitting
- [x] You reference which issue is being closed in the PR text

✨✨ 😄 Thanks so much for contributing to wasm-pack! 😄 ✨✨
---
Fixes #191

### CODE REVIEW

**Comment by SoryRawyer** [comment]
Sorry about that! I just re-ran rustfmt and pushed the change.

**Comment by mgattozzi** [comment]
Awesome thanks! Once that passes again I'll merge it :D

**Comment by mgattozzi** [comment]
Thanks a lot @SoryRawyer for cleaning this up! :D

**Comment by SoryRawyer** [comment]
np! Thanks for reviewing + merging!

**Pull request merged**
