### PR TITLE
bump: wasm_opt, chromedriver & geckodriver version

### PR DESCRIPTION
**Pull request by meck93**
Make sure these boxes are checked! 📦✅
- [x] You have the latest version of `rustfmt` installed
- [x] You ran `cargo fmt` on the code base before submitting
- [x] You reference which issue is being closed in the PR text

### Description
Fixes the issue reported in #919

### CODE REVIEW

**Comment by lucashorward** [comment]
Seems good, but the download urls have changed (since the binaries in the release have a different naming convention now, it seems - https://github.com/WebAssembly/binaryen/releases), so if you could rename those accordingly, that would be great!

**Comment by meck93** [comment]
Hi @lucashorward 
Thanks for the reply. Maybe I don't fully understand what you mean. Could you be a bit more specific? 

The download URL for **binaryen** version_97 looks like this: https://github.com/WebAssembly/binaryen/releases/download/version_97/binaryen-version_97-x86_64-linux.tar.gz

And, this is the way that we already compose it:  
```Rust
Ok(format!(
    "https://github.com/WebAssembly/binaryen/releases/download/{vers}/binaryen-{vers}-{target}.tar.gz",
    vers = "version_97",
    target = target,
))
```         

Or, did you mean something different?

**Comment by lucashorward** [comment]
Yes, that is the url I mean, and I see you've correctly updated the target variable that's used in that link for linux (which has changed from `x86-linux` to `x86_64-linux`- in `src/install/mod.rs` line 167), but the path has also changed for windows and macos in this newer release of wasm_opt. So those paths should be updated here as well:
For 64-bit macos, it should go from `x86_64-apple-darwin` to `x86_64-macos` (line 176)
For 64-bit windows, it should go from `x86-windows` to `x86_64-windows` (line 179)

The failing CI test is because of this, the url for linux is correct but for the other systems a 404 is returned.

On top of that, I see there are no 32-bit versions listed - not sure what the impact of that will be to be honest. Maybe @ashleygwilliams has an idea on that. On the one hand, we don't want to keep using this older version, but I'm unsure if this will break all 32-bit builds.

**Comment by meck93** [comment]
Thanks a lot for the clarification! That makes a lot of sense. I'm on Linux and that's probably why I only updated the Linux URL when I compiled `wasm-pack` locally (before opening the PR). But I'll fix the other ones as well!

**Comment by drager** [comment]
Already fixed in new releases.

**Pull request closed without merging**
