### PR TITLE
Fix logs for uniformity (#716)

### PR DESCRIPTION
**Pull request by petosorus**

### CODE REVIEW

**Comment by petosorus** [comment]
Yeah, I'm a bit dumb and made this change a bit too quickly. Thanks for the feedback.

**Comment by petosorus** [comment]
Regarding the broken test, should I change `"[WARN]: \"package.metadata.wasm-...` to `"[WARN]: :-) \"package.metadata.wasm-...` as the reference string we test against, or do you think there's a way to ignore the `:-)` part as it's not that important, and maybe subject to change?

This is in `manifest.rs`, line 451. I don't know if `predicates::str::contains` would allow something like a regex similar to this `"[WARN]: (:-\))? \"package.metadata.wasm-`

**Comment by drager** [comment]
> Regarding the broken test, should I change `"[WARN]: \"package.metadata.wasm-...` to `"[WARN]: :-) \"package.metadata.wasm-...` as the reference string we test against, or do you think there's a way to ignore the `:-)` part as it's not that important, and maybe subject to change?
> 
> This is in `manifest.rs`, line 451. I don't know if `predicates::str::contains` would allow something like a regex similar to this `"[WARN]: (:-\))? \"package.metadata.wasm-`

Yeah, I think you can check for `[WARN]: :)`

**Comment by petosorus** [comment]
Hi! I'm still not too sure about rebase, should have done what's needed :)

**Comment by drager** [comment]
@petosorus Thanks! It looks good! There's something weird going on with the checks. Once those passes we can get this merged :blush:

**Review by ashleygwilliams — APPROVED** [review]

**Pull request merged**
