### PR TITLE
fix(exe): wasm-pack-init (1).exe should work

### LINKED ISSUE #518: wasm-pack-init (1).exe does not show init instructions
When i download new version wasm-pack, my browser saved it as wasm-pack-init (1).exe.

wasm-pack-init (1).exe does not show init instructions and work as wasm-pack.exe

Maybe run all the files with name start from "wasm-pack-init" as init-file?

### PR DESCRIPTION
**Pull request by ashleygwilliams**
🔕 do no merge 🔕 

fixes #518 

@alexcrichton how should we test this? (if at all?) are there security implications for not doing the exact match that i'm not thinking of?

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
@fitzgen or @alexcrichton do either of you have access to a windows machine to manually test this? unfortunately mine is in Austin and i am not.

**Comment by alexcrichton** [comment]
I, unfortunately, do no

**Comment by fitzgen** [comment]
Sorry :(

**Comment by Pauan** [comment]
@ashleygwilliams I have Windows 10, I'll try and reproduce the issue (and verify the fix).

**Comment by ashleygwilliams** [comment]
thank you so much @Pauan i really appreciate it! i was able to reproduce the error on my machine when it was originally reported

**Comment by ashleygwilliams** [comment]
thank you so much @Pauan !!

**Pull request merged**
