### PR TITLE
Build crate in a workspace

### PR DESCRIPTION
**Pull request by fitzgen**
Make sure these boxes are checked! 📦✅

- [X] You have the latest version of `rustfmt` installed and have your 
      cloned directory set to nightly
```bash
$ rustup override set nightly
$ rustup component add rustfmt-preview --toolchain nightly
```
- [X] You ran `rustfmt` on the code base before submitting
- [X] You reference which issue is being closed in the PR text

✨✨ 😄 Thanks so much for contributing to wasm-pack! 😄 ✨✨

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me, but looks like rustfmt on CI disagrees with your local rustfmt?

**Comment by fitzgen** [comment]
Huh. I did a rustup and still I'm not getting any more diffs... I wonder if Travis is using an old Rust??

**Comment by alexcrichton** [comment]
Stable vs nightly perhaps?

**Comment by fitzgen** [comment]
I just double checked that our CI config was using nightly (and did https://github.com/rustwasm/wasm-pack/pull/432 at the same time) and confirmed that yes it is. And I am also using nightly...

**Comment by fitzgen** [comment]
Added some logging of the rustfmt version to #432

**Comment by fitzgen** [comment]
Looks like I *am* using an out-of-date rustfmt!

Mine:

```
$ cargo fmt --version
rustfmt 0.99.5-nightly (90692a5 2018-09-26)
```

[Theirs](https://travis-ci.org/rustwasm/wasm-pack/jobs/451112370#L2277):

```
$ cargo fmt --version
rustfmt 0.99.6-nightly (750b252 2018-10-18)
```

But I can't update mine further...

```
$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'beta-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2018-11-05, rust version 1.32.0-nightly (e6c5cf923 2018-11-04)
error: component 'clippy-preview' for 'x86_64-unknown-linux-gnu' is unavailable for download
info: checking for self-updates

       stable-x86_64-unknown-linux-gnu unchanged - rustc 1.30.0 (da5f414c2 2018-10-24)
         beta-x86_64-unknown-linux-gnu unchanged - rustc 1.31.0-beta.4 (04da282bb 2018-11-01)
  nightly-x86_64-unknown-linux-gnu update failed - rustc 1.31.0-nightly (2bd5993ca 2018-10-02)

$ cargo fmt --version
rustfmt 0.99.5-nightly (90692a5 2018-09-26)
```

**Comment by fitzgen** [comment]
Huh, looks like it was clippy holding me back

```
error: component 'clippy-preview' for 'x86_64-unknown-linux-gnu' is unavailable for download
```

**Pull request merged**
