### PR TITLE
[WIP] fix(release): update appveyor config

### LINKED ISSUE #147: debug build windows appveyor releases
we currently make release binaries for linux and mac using travis. we should also do this for windows with appveyor!

### PR DESCRIPTION
**Pull request by ashleygwilliams**
fixes #147

### CODE REVIEW

**Comment by mgattozzi** [comment]
Looks like the build failed cause it was cancelled? Oh is that what the vTEST tag was for?

**Comment by ashleygwilliams** [comment]
yeah i was poking around trying to get this to work. it's something fiddly like when i did this for travis. not sure what tho.

**Comment by mgattozzi** [comment]
For the record I always hate setting CI up for projects because getting it to work is hard :( ugh hm let me think about it maybe I'll come up with something for this predicament

**Comment by ashleygwilliams** [comment]
closing as alex took care of this in another PR 🎉

**Pull request closed without merging**
