### PR TITLE
[WIP] Add --target electron-renderer (for generating electron preloads)

### PR DESCRIPTION
**Pull request by darinmorrison**
This is a companion PR to https://github.com/rustwasm/wasm-bindgen/pull/1928. Please see there for more info. I haven't created an issue or RFC for this yet but would like to open a draft PR in case anyone has feedback in the meantime.

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
@darinmorrison this is exciting! let me know how i can help!

**Comment by ashleygwilliams** [comment]
throwing a blocked label on here as we wait for the wasm-bindgen PR to shake out :)

**Comment by xrmx** [comment]
Looks like an alternative solution got applied in wasm-bindgen https://github.com/rustwasm/wasm-bindgen/pull/1958

**Comment by darinmorrison** [comment]
@ashleygwilliams I ended up submitting another PR upstream to `wasm-bindgen-cli` that takes a different approach to supporting electron. This newer approach does not need its own target but just adds an `--omit-imports` flag. I've created a new PR for that at https://github.com/rustwasm/wasm-pack/pull/799 so I'll close this one.

**Pull request closed without merging**
