### PR TITLE
Copy fixtures to temp dir

### PR DESCRIPTION
**Pull request by fitzgen**
Make sure these boxes are checked! 📦✅

- [X] You have the latest version of `rustfmt` installed and have your 
      cloned directory set to nightly
```bash
$ rustup override set nightly
$ rustup component add rustfmt-preview --toolchain nightly
```
- [X] You ran `rustfmt` on the code base before submitting
- [ ] ~~You reference which issue is being closed in the PR text~~

✨✨ 😄 Thanks so much for contributing to wasm-pack! 😄 ✨✨

### CODE REVIEW

**Comment by migerh** [comment]
Just wanted to leave a quick note that tempdir is deprecated in favor of tempfile: https://github.com/rust-lang-deprecated/tempdir/issues/45

**Comment by fitzgen** [comment]
test

**Comment by ashleygwilliams** [comment]
@fitzgen after #220 this will need a rebase- otherwise i think it looks good to me and i'll merge :)

**Pull request merged**
