### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by hamza1311**
Updates: 
- Clap
- toml
- predicates
- serial_test

Make sure these boxes are checked! 📦✅

- [x] You have the latest version of `rustfmt` installed
```bash
$ rustup component add rustfmt
```
- [x] You ran `cargo fmt` on the code base before submitting
- [ ] You reference which issue is being closed in the PR text

✨✨ 😄 Thanks so much for contributing to wasm-pack! 😄 ✨✨

### CODE REVIEW

**Comment by hamza1311** [comment]
I ran the failing tests locally and they pass, not sure what's happening in the CI

**Comment by drager** [comment]
@hamza1311 Tests have been fixed in master now. Could you perhaps rebase master into your branch?

**Comment by hamza1311** [comment]
@drager done

**Review by drager — APPROVED** [review]
Thank you!

**Pull request merged**
