### PR TITLE
pre-build before wasm-pack publish

### LINKED ISSUE #438: publish should automatically run build if necessary
If I run `wasm-pack publish` it should automatically run `wasm-pack build` for me if necessary.

For example, if I don't even have the `pkg` directory yet, it should handle that.

### PR DESCRIPTION
**Pull request by csmoe**
Closes #438

### CODE REVIEW

**Comment by csmoe** [comment]
@ashleygwilliams that's great, so I'll expand the features soon as you wrote.

**Comment by csmoe** [comment]
@ashleygwilliams 
peek 2018-12-26 21-55

**Comment by csmoe** [comment]
@ashleygwilliams 
>  it may also be nice to list the defaults/options for out dir and target options when prompting

it already does, default options indicated within `[...]` as the demo shows(I just `Enter` to choose the default). but for clarifying, I'll add "default" keyword to the prompt.

**Comment by csmoe** [comment]
peek 2018-12-28 10-54
done

**Comment by csmoe** [comment]
@ashleygwilliams btw, may I still have your invitation of rustwasm-org as we talked in twitter several months ago?

**Comment by ashleygwilliams** [comment]
oh yes! i'll take care of that today :)

**Pull request merged**
