### PR TITLE
Add suppot for more platforms to installer script

### PR DESCRIPTION
**Pull request by omninonsense**
This makes the installation script work on M1 macs, as well as inside docker (especially when combined with buildx) for aarch64/arm64 architectures.

Related:
 - https://github.com/rustwasm/wasm-pack/issues/1064
 - https://github.com/rustwasm/wasm-pack/issues/952
 - https://github.com/rustwasm/wasm-pack/issues/1125

### CODE REVIEW

**Comment by gthb** [comment]
There's a bunch of open issues about M1 support, should this be marked as closing some of them? https://github.com/rustwasm/wasm-pack/issues?q=is%3Aissue+is%3Aopen+m1

**Comment by omninonsense** [comment]
Hi! Thanks for taking a look at this. So, I tried to look again with a few more different searches now, and it might help with https://github.com/rustwasm/wasm-pack/issues/1064

**Comment by omninonsense** [comment]
Seems to fail for unrelated reasons

**Comment by omninonsense** [comment]
Hi, @gthb, are you the right person to look into merging this, or do we just wait for it to get picked up by the maintainers?

**Comment by gthb** [comment]
> Hi, @gthb, are you the right person to look into merging this, or do we just wait for it to get picked up by the maintainers?

I think only @drager has the admin bit, or at least is the only one who has been acting on some PRs in recent months.

**Review by drager — APPROVED** [review]
Thank you!

**Pull request merged**
