### PR TITLE
Adding in `--quiet` and `--log-level` flags

### PR DESCRIPTION
**Pull request by Pauan**

### CODE REVIEW

**Comment by Pauan** [comment]
> I wonder however if --quiet should mean that we don't emit any output at all and just use the exit code.

I did consider that, however I *do* actually want the `cargo build` output to show, since building a crate can take a long time and the user wants to see progress being made.

(It's possible to achieve full silence by using `wasm-pack --quiet build -- --quiet` though that's very non-obvious)

So maybe this should actually be a different flag, something like `--message-format none` (analogous to `cargo --message-format`)?

**Comment by Pauan** [comment]
Okay, I changed `--quiet` so it also silences output from `cargo`.

And I added in a new `--log-level` flag which controls wasm-pack's log level. So the previous behavior of `--quiet` can be achieved by using `--log-level error`.

**Comment by Pauan** [comment]
> can we add a test and some docs?

I don't mind, but the existing CLI flags (e.g. `verbose`) don't have that. So where would I put it?

**Comment by Pauan** [comment]
(Just a heads up that I added in `-q` as a short-hand for `--quiet`, which is consistent with `cargo`)

**Comment by ashleygwilliams** [comment]
@Pauan i'd probably create a new doc under commands about log level! https://rustwasm.github.io/wasm-pack/book/commands/index.html

**Comment by Pauan** [comment]
@ashleygwilliams I added in docs and unit tests.

**Comment by Pauan** [comment]
@ashleygwilliams Ping.

**Comment by Pauan** [comment]
@ashleygwilliams Ping.

**Comment by niedzielski** [comment]
This is a subtle but important change as verbose informational output is useful for debugging but may conceal important issues. ([Silence is golden!](https://en.wikipedia.org/wiki/Unix_philosophy#Eric_Raymond's_17_Unix_Rules))

**Comment by Pauan** [comment]
@ashleygwilliams This is ready for review.

**Pull request merged**
