### PR TITLE
Support wasm-dis

### LINKED ISSUE #748: Add compile crate to WAT
## 💡 Feature description
Add support for WAT (WebAssembly Text) as an output of `wasm-pack`. It would nice to be able look at the completed library and see what WASM was generated without needing to use another tool.

#### 💻 Basic example
```
wasp-pack build --wat
```

### PR DESCRIPTION
**Pull request by csmoe**
Closes #748

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
hey @csmoe ! this is marked as a draft- definitely a feature i'd love to see, anything i can do to help move this  forward?

**Comment by csmoe** [comment]
@ashleygwilliams sorry for the delay, more commits soon.

**Comment by csmoe** [comment]
@ashleygwilliams review notes:
1. this PR contains a refactoring of third-party tools, making it easier to introduce more tools in the future.
2. wasm-dis will be exec'd after `opt` if `wasm-opt` is enabled.
image
image

**Comment by csmoe** [comment]
@ashleygwilliams review notes:
1. this PR contains a refactoring of third-party tools, making it easier to introduce more tools in the future.
2. wasm-dis will be exec'd after `opt` if `wasm-opt` is enabled.
image

**Comment by csmoe** [comment]
@ashleygwilliams The test failure seems unrelated to this change set.

**Comment by csmoe** [comment]
@ashleygwilliams @Pauan sorry for disconnection, would you mind having a review? thankins :)

**Comment by Pauan** [comment]
@csmoe Sorry, I don't contribute to Rust anymore. Ashley is trying to find a maintainer for wasm-pack:

https://github.com/rustwasm/wasm-pack/issues/914
https://github.com/rustwasm/wasm-pack/issues/928

**Comment by csmoe** [comment]
It has been a while without response, closing for not blocking the progress of https://github.com/rustwasm/wasm-pack/issues/820.

**Comment by raphamorim** [comment]
Hey there @csmoe @ashleygwilliams this change would be nice to have. Let me know if I could take the work on it 👍

**Comment by csmoe** [comment]
@raphamorim yep 😀

**Pull request closed without merging**
